const http = require('node:http'); const fs = require('node:fs'); const path = require('node:path');
const store = require('./store'); const tools = require('./tools'); const llm = require('./llm'); const v2Skills = require('./v2-skills'); const v2Data = require('./v2-data'); const documents = require('./v2-documents'); const research = require('./v2-research'); const developer = require('./v2-developer'); const connectors = require('./v2-connectors'); const { createPathPolicy } = require('./path-policy'); const { createSkills } = require('./skills'); const { createRegistry } = require('./registry'); const { createAssistant } = require('./assistant');
const PORT = Number(process.env.PORT || 4111); const HOST = process.env.NOUR_BIND_HOST || '127.0.0.1'; const publicDir = path.join(__dirname, '..', 'public'); const policy = createPathPolicy(); const registry = createRegistry({ store, skills: createSkills({ store, policy, tools }) }); const assistant = createAssistant({ registry, store });
function send(res, status, value, type = 'application/json') { res.writeHead(status, { 'Content-Type': `${type}; charset=utf-8`, 'Cache-Control': 'no-store' }); res.end(type === 'application/json' ? JSON.stringify(value) : value); }
function body(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', c => { raw += c; if (raw.length > 1e6) req.destroy(); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('Invalid JSON')); } }); }); }
function nextOccurrence(value, recurrence) { const date = new Date(value); if (recurrence === 'daily') date.setDate(date.getDate() + 1); else if (recurrence === 'weekly') date.setDate(date.getDate() + 7); else if (recurrence === 'monthly') date.setMonth(date.getMonth() + 1); return date.toISOString(); }
function dueReminders() { const data = store.read(); const now = Date.now(); const dueEvents = []; let changed = false; for (const reminder of data.reminders) if (reminder.status === 'scheduled' && new Date(reminder.dueAt) <= now) { dueEvents.push(reminder); if (['daily', 'weekly', 'monthly'].includes(reminder.recurrence)) { do { reminder.dueAt = nextOccurrence(reminder.dueAt, reminder.recurrence); } while (new Date(reminder.dueAt) <= now); } else reminder.status = 'due'; changed = true; } if (changed) store.write(data); for (const reminder of dueEvents) store.log('reminder.due', reminder.title, { reminderId: reminder.id }); return store.read().reminders; }
const server = http.createServer(async (req, res) => { const url = new URL(req.url, `http://${req.headers.host}`); const route = url.pathname; try {
  if (route === '/api/health') return send(res, 200, { ok: true, name: 'Nour Local', version: '1.0.0', host: HOST });
  if (route === '/api/state' && req.method === 'GET') { const data = store.read(); return send(res, 200, { memories: data.memories, reminders: dueReminders(), tasks: data.tasks, goals: data.goals, pendingActions: data.pendingActions.filter(a => a.status === 'pending').map(({ id, skill, permission, summary, status }) => ({ actionId: id, skill, permission, summary, status })), activity: data.activity, system: tools.systemInfo(), notification: data.notification, llm: llm.publicConfig(), skills: registry.skills(), v2Skills: v2Skills.publicCatalog(store, registry.skills()), connectors: connectors.publicConnectors(store) }); }
  if (route === '/api/chat' && req.method === 'POST') { const input = await body(req); return send(res, 200, await assistant.respond(input.text, { conversationId: input.conversationId || 'default' })); }
  if (route === '/api/chat/stream' && req.method === 'POST') { const input = await body(req); res.writeHead(200, { 'Content-Type': 'text/event-stream; charset=utf-8', 'Cache-Control': 'no-cache', Connection: 'keep-alive' }); try { const messages = [{ role: 'user', content: String(input.text || '').slice(0, 12000) }]; const full = await llm.askStream(messages, token => res.write(`data: ${JSON.stringify({ token })}\n\n`)); if (full === null) res.write(`data: ${JSON.stringify({ error: 'No configured LLM connection.' })}\n\n`); else { store.log('llm.stream_completed', 'Streaming response'); res.write(`data: ${JSON.stringify({ done: true })}\n\n`); } } catch (error) { store.log('llm.stream_failed', error.message, { success: false }); res.write(`data: ${JSON.stringify({ error: error.message })}\n\n`); } res.end(); return; }
  if (route === '/api/actions/approve' && req.method === 'POST') { const input = await body(req); if (typeof input.actionId !== 'string' || input.actionId.length > 100 || typeof input.approved !== 'boolean') return send(res, 400, { error: 'Invalid approval request.' }); return send(res, 200, await registry.approve(input.actionId, input.approved)); }
  if (route === '/api/actions' && req.method === 'GET') return send(res, 200, { actions: store.read().pendingActions });
  if (route === '/api/llm' && req.method === 'POST') return send(res, 200, llm.saveConfig(await body(req)));
  if (route === '/api/llm/select' && req.method === 'POST') { const input = await body(req); return send(res, 200, llm.selectConfig(input.profileId)); }
  if (route === '/api/tasks' && req.method === 'GET') return send(res, 200, { tasks: store.read().tasks });
  if (route === '/api/tasks' && req.method === 'POST') { const input = await body(req); const result = await registry.request('tasks.create', input); return send(res, result.status === 'rejected' ? 400 : 200, result); }
  if (route.startsWith('/api/tasks/') && req.method === 'PATCH') { const task = store.updateTask(route.split('/').pop(), await body(req)); return task ? send(res, 200, { status: 'completed', data: task, text: 'Task updated.' }) : send(res, 404, { error: 'Task not found.' }); }
  if (route === '/api/goals' && req.method === 'GET') return send(res, 200, { goals: store.read().goals });
  if (route === '/api/goals' && req.method === 'POST') { const result = await registry.request('goals.create', await body(req)); return send(res, result.status === 'rejected' ? 400 : 200, result); }
  if (route.startsWith('/api/goals/') && req.method === 'PATCH') { const goal = store.updateGoal(route.split('/').pop(), await body(req)); return goal ? send(res, 200, { status: 'completed', data: goal, text: 'Goal updated.' }) : send(res, 404, { error: 'Goal not found.' }); }
  if (route === '/api/reminders' && req.method === 'GET') return send(res, 200, { reminders: dueReminders() });
  if (route === '/api/reminders' && req.method === 'POST') { const result = await registry.request('reminders.create', await body(req)); return send(res, result.status === 'rejected' ? 400 : 200, result); }
  if (route.startsWith('/api/reminders/') && req.method === 'PATCH') { const reminder = store.updateReminder(route.split('/').pop(), await body(req)); return reminder ? send(res, 200, { status: 'completed', data: reminder, text: 'Reminder updated.' }) : send(res, 404, { error: 'Reminder not found.' }); }
  if (route === '/api/memories' && req.method === 'GET') { const query = url.searchParams.get('q')?.toLowerCase(); const memories = store.read().memories.filter(m => !query || m.text.toLowerCase().includes(query)); return send(res, 200, { memories }); }
  if (route === '/api/notification-preferences' && req.method === 'POST') { const input = await body(req); const preference = store.setNotificationPreference(input.enabled); store.log('notification.preference_changed', preference.enabled ? 'Browser notifications enabled' : 'Browser notifications disabled'); return send(res, 200, { status: 'completed', notification: preference }); }
  if (route === '/api/activity' && req.method === 'GET') return send(res, 200, { activity: store.read().activity });
  if (route === '/api/conversations' && req.method === 'GET') { const conversations = Object.entries(store.read().conversations || {}).filter(([, value]) => !value.persistenceDisabled).map(([id, value]) => ({ id, updatedAt: value.updatedAt, messageCount: value.messages?.length || 0 })); return send(res, 200, { conversations }); }
  if (route.startsWith('/api/conversations/') && req.method === 'GET') { const parts = route.split('/').slice(3).map(decodeURIComponent); const conversation = store.read().conversations?.[parts[0]]; if (!conversation || conversation.persistenceDisabled) return send(res, 404, { error: 'Conversation not found.' }); const messages = conversation.messages || []; if (parts[1] === 'export') { const markdown = messages.map(message => `## ${message.role}\n\n${message.content}\n`).join('\n'); return send(res, 200, { status: 'completed', format: 'markdown', content: markdown, conversationId: parts[0] }); } return send(res, 200, { conversationId: parts[0], messages }); }
  if (route === '/api/skills' && req.method === 'GET') return send(res, 200, { skills: v2Skills.publicCatalog(store, registry.skills()) });
  if (route === '/api/skills/configure' && req.method === 'POST') { const input = await body(req); return send(res, 200, { status: 'completed', skills: v2Skills.setEnabled(store, input.id, input.enabled) }); }
  if (route === '/api/custom-skills' && req.method === 'GET') return send(res, 200, { skills: store.read().customSkills || [] });
  if (route === '/api/custom-skills' && req.method === 'POST') return send(res, 200, { status: 'completed', skill: v2Skills.registerCustom(store, await body(req)) });
  for (const type of Object.keys(v2Data.definitions)) { const base = `/api/v2/${type}`; if (route === base && req.method === 'GET') return send(res, 200, { status: 'completed', data: v2Data.list(store, type) }); if (route === base && req.method === 'POST') return send(res, 200, { status: 'completed', data: v2Data.create(store, type, await body(req)) }); if (route.startsWith(`${base}/`) && req.method === 'PATCH') return send(res, 200, { status: 'completed', data: v2Data.update(store, type, route.slice(base.length + 1), await body(req)) }); if (route.startsWith(`${base}/`) && req.method === 'DELETE') return send(res, 200, { status: 'completed', data: v2Data.remove(store, type, route.slice(base.length + 1)) }); }
  if (route === '/api/v2/documents/read' && req.method === 'POST') return send(res, 200, { status: 'completed', success: true, data: await documents.extractDocument(policy, await body(req)) });
  if (route === '/api/v2/documents/summarize' && req.method === 'POST') return send(res, 200, { status: 'completed', success: true, data: await documents.summarize(policy, await body(req), llm.ask) });
  if (route === '/api/v2/documents/compare' && req.method === 'POST') return send(res, 200, { status: 'completed', success: true, data: documents.compare(policy, await body(req)) });
  if (route === '/api/v2/documents/compare-summary' && req.method === 'POST') return send(res, 200, { status: 'completed', success: true, data: await documents.compareWithLLM(policy, await body(req), llm.ask) });
  if (route === '/api/v2/web-research/fetch' && req.method === 'POST') return send(res, 200, { status: 'completed', success: true, data: await research.fetchSource(await body(req)) });
  if (route === '/api/v2/developer/inspect' && req.method === 'POST') return send(res, 200, { status: 'completed', success: true, data: developer.inspect(policy, await body(req)) });
  if (route === '/api/v2/email/send' && req.method === 'POST') return send(res, 200, await registry.request('email.send', await body(req)));
  if (route === '/api/connectors' && req.method === 'GET') return send(res, 200, { connectors: connectors.publicConnectors(store) });
  if (route.startsWith('/api/connectors/') && route.endsWith('/configure') && req.method === 'POST') return send(res, 200, { status: 'completed', connectors: connectors.save(store, route.split('/')[3], await body(req)) });
  if (route.startsWith('/api/connectors/') && route.endsWith('/enable') && req.method === 'POST') { const input = await body(req); return send(res, 200, { status: 'completed', connectors: connectors.setEnabled(store, route.split('/')[3], input.enabled) }); }
  const requested = route === '/' ? 'index.html' : route.slice(1); const file = path.resolve(publicDir, requested); if (!file.startsWith(publicDir) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) return send(res, 404, { error: 'Not found' }); const type = file.endsWith('.css') ? 'text/css' : file.endsWith('.js') ? 'application/javascript' : file.endsWith('.webmanifest') ? 'application/manifest+json' : file.endsWith('.svg') ? 'image/svg+xml' : 'text/html'; return send(res, 200, fs.readFileSync(file, 'utf8'), type); } catch (error) { store.log('api.error', error.message, { success: false }); send(res, 400, { error: error.message }); } });
if (require.main === module) server.listen(PORT, HOST, () => console.log(`Nour Local is ready at http://${HOST}:${PORT}`));
module.exports = { server, dueReminders, registry, policy };
