const store = require('./store');
const credentials = require('./credentials');

function runtimeConfig() {
  const data = store.read(); const config = { ...(data.llm || {}) }; const envKey = process.env.NOUR_LLM_API_KEY || '';
  if (envKey) { config.enabled = process.env.NOUR_LLM_ENABLED !== 'false'; config.provider = process.env.NOUR_LLM_PROVIDER || config.provider || 'OpenAI-compatible'; config.baseUrl = process.env.NOUR_LLM_BASE_URL || config.baseUrl || 'https://api.openai.com/v1'; config.model = process.env.NOUR_LLM_MODEL || config.model || 'gpt-4o-mini'; config.apiKey = credentials.seal(envKey); }
  return config;
}
function publicConfig() {
  const data = store.read(); let migrated = false;
  if (!(data.llmProfiles || []).length && data.llm?.apiKey) { const profile = { ...data.llm, id: store.id('llm'), name: data.llm.provider || 'Saved connection', apiKey: credentials.seal(data.llm.apiKey) }; data.llmProfiles = [profile]; data.activeLlmId = profile.id; data.llm = profile; migrated = true; }
  for (const profile of data.llmProfiles || []) if (profile.apiKey && !credentials.isSealed(profile.apiKey)) { profile.apiKey = credentials.seal(profile.apiKey); migrated = true; }
  if (data.llm?.apiKey && !credentials.isSealed(data.llm.apiKey)) { data.llm.apiKey = credentials.seal(data.llm.apiKey); migrated = true; }
  if (migrated) store.write(data); const llm = runtimeConfig();
  return { ...llm, apiKeySet: Boolean(credentials.unseal(llm.apiKey)), apiKey: undefined, activeProfileId: data.activeLlmId, profiles: (data.llmProfiles || []).map(profile => ({ id: profile.id, name: profile.name, provider: profile.provider, model: profile.model, baseUrl: profile.baseUrl, enabled: Boolean(profile.enabled), apiKeySet: Boolean(credentials.unseal(profile.apiKey)) })) };
}
function saveConfig(input) {
  const data = store.read(); const provider = String(input.provider || 'OpenAI-compatible'); const claude = /claude|anthropic/i.test(provider); const suppliedBase = String(input.baseUrl || ''); const suppliedModel = String(input.model || ''); const existing = (data.llmProfiles || []).find(profile => profile.id === input.profileId); const rawApiKey = input.apiKey === '••••••••' ? credentials.unseal(existing?.apiKey || data.llm.apiKey) : String(input.apiKey || ''); const apiKey = credentials.seal(rawApiKey);
  const profile = { id: existing?.id || store.id('llm'), name: String(input.profileName || existing?.name || provider), enabled: Boolean(input.enabled) || Boolean(rawApiKey), provider, baseUrl: (claude && (!suppliedBase || suppliedBase.includes('api.openai.com'))) ? 'https://api.anthropic.com' : (suppliedBase || 'https://api.openai.com/v1').replace(/\/$/, ''), model: (claude && (!suppliedModel || suppliedModel === 'gpt-4o-mini')) ? 'claude-3-5-sonnet-latest' : (suppliedModel || 'gpt-4o-mini'), apiKey };
  data.llmProfiles = data.llmProfiles || []; const index = data.llmProfiles.findIndex(item => item.id === profile.id); if (index >= 0) data.llmProfiles[index] = profile; else data.llmProfiles.unshift(profile); data.activeLlmId = profile.id; data.llm = profile; store.write(data); store.log('llm.configured', `${data.llm.provider}: ${data.llm.model || 'no model selected'}`); return publicConfig();
}
function selectConfig(profileId) { const data = store.read(); const profile = (data.llmProfiles || []).find(item => item.id === profileId); if (!profile) throw new Error('Saved connection not found.'); data.activeLlmId = profile.id; data.llm = profile; store.write(data); store.log('llm.selected', `${profile.name}: ${profile.provider}`); return publicConfig(); }
async function ask(messages) {
  const config = runtimeConfig(); const apiKey = credentials.unseal(config.apiKey); if (!config.enabled || !config.baseUrl || !config.model) return null;
  if (/claude|anthropic/i.test(config.provider || '')) { const system = messages.filter(message => message.role === 'system').map(message => message.content).join('\n'); const response = await fetch(`${config.baseUrl}/v1/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-api-key': apiKey || '', 'anthropic-version': '2023-06-01' }, body: JSON.stringify({ model: config.model, max_tokens: 1200, ...(system ? { system } : {}), messages: messages.filter(message => message.role !== 'system') }) }); if (!response.ok) throw new Error(`Claude request failed (${response.status}): ${await response.text()}`); const body = await response.json(); return body.content?.filter(part => part.type === 'text').map(part => part.text).join('') || 'Claude returned no text.'; }
  const response = await fetch(`${config.baseUrl}/chat/completions`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(apiKey ? { Authorization: `Bearer ${apiKey}` } : {}) }, body: JSON.stringify({ model: config.model, messages, temperature: 0.4 }) }); if (!response.ok) throw new Error(`LLM request failed (${response.status}): ${await response.text()}`); const body = await response.json(); return body.choices?.[0]?.message?.content || 'The configured model returned no text.';
}
async function askStream(messages, onToken) {
  const config = runtimeConfig(); const apiKey = credentials.unseal(config.apiKey); if (!config.enabled || !config.baseUrl || !config.model) return null; const claude = /claude|anthropic/i.test(config.provider || ''); const response = await fetch(claude ? `${config.baseUrl}/v1/messages` : `${config.baseUrl}/chat/completions`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(claude ? { 'x-api-key': apiKey || '', 'anthropic-version': '2023-06-01' } : { ...(apiKey ? { Authorization: `Bearer ${apiKey}` } : {}) }) }, body: JSON.stringify(claude ? { model: config.model, max_tokens: 1200, stream: true, system: messages.filter(message => message.role === 'system').map(message => message.content).join('\n'), messages: messages.filter(message => message.role !== 'system') } : { model: config.model, messages, temperature: 0.4, stream: true }) }); if (!response.ok) throw new Error(`LLM streaming request failed (${response.status}): ${await response.text()}`); if (!response.body) throw new Error('LLM provider did not return a stream.'); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ''; let full = ''; const consume = raw => { buffer += raw; const lines = buffer.split(/\r?\n/); buffer = lines.pop() || ''; for (const line of lines) { if (!line.startsWith('data:')) continue; const value = line.slice(5).trim(); if (!value || value === '[DONE]') continue; try { const json = JSON.parse(value); const token = claude ? json.delta?.text : json.choices?.[0]?.delta?.content; if (token) { full += token; onToken(token); } } catch {} } }; while (true) { const { value, done } = await reader.read(); if (done) break; consume(decoder.decode(value, { stream: true })); } return full;
}
module.exports = { publicConfig, saveConfig, selectConfig, ask, askStream };
