const fs = require('node:fs'); const credentials = require('./credentials');
const path = require('node:path');
const os = require('node:os');
const { Permission } = require('./permissions');

const text = (value, label, max = 500) => { if (typeof value !== 'string' || !(value = value.trim()) || value.length > max) throw new Error(`Invalid ${label}.`); return value; };
const folderName = value => { value = text(value, 'folder name', 120); if (value === '.' || value === '..' || /[\\/:*?"<>|]/.test(value)) throw new Error('Folder name contains invalid characters.'); return value; };
const taskInput = input => ({ title: text(input.title, 'task title', 240), description: input.description ? text(input.description, 'task description', 1000) : '', priority: ['low', 'medium', 'high'].includes(input.priority) ? input.priority : 'medium', dueAt: input.dueAt ? new Date(input.dueAt).toISOString() : null, project: input.project ? text(input.project, 'project', 120) : null, important: Boolean(input.important), tags: Array.isArray(input.tags) ? input.tags.slice(0, 10).map(tag => text(tag, 'tag', 40)) : [], repeat: ['daily', 'weekly', 'monthly'].includes(input.repeat) ? input.repeat : null });
const goalInput = input => ({ title: text(input.title, 'goal title', 240), description: input.description ? text(input.description, 'goal description', 1000) : '', priority: ['low', 'medium', 'high'].includes(input.priority) ? input.priority : 'medium', dueAt: input.dueAt ? new Date(input.dueAt).toISOString() : null });

function createSkills({ store, policy, tools }) {
  return [
    { id: 'memory.save', name: 'Save memory', description: 'Saves an explicitly requested memory.', permission: Permission.READ, inputSchema: i => ({ text: text(i.text, 'memory', 1000) }), summary: i => 'Save an explicit memory', execute: async i => { const memory = store.addMemory(i.text); return { text: `Stored in long-term memory: “${memory.text}”.`, data: memory }; } },
    { id: 'memory.search', name: 'Search memory', description: 'Finds explicit memories.', permission: Permission.READ, inputSchema: i => ({ query: text(i.query, 'memory search', 200) }), summary: () => 'Search memory', execute: async i => { const memories = store.read().memories.filter(m => m.text.toLowerCase().includes(i.query.toLowerCase())).slice(0, 20); return { text: memories.length ? memories.map(m => `• ${m.text}`).join('\n') : 'No matching memories.', data: memories }; } },
    { id: 'memory.forget', name: 'Forget memory', description: 'Removes matching explicit memories.', permission: Permission.APPROVAL_REQUIRED, inputSchema: i => ({ query: text(i.query, 'memory query', 200) }), summary: i => `Forget memories matching “${i.query}”`, execute: async i => { const count = store.forgetMemory(i.query); return { text: count ? `Forgot ${count} memory item(s).` : 'No matching memories to forget.', data: { count } }; } },
    { id: 'tasks.create', name: 'Create task', description: 'Creates a lightweight task.', permission: Permission.READ, inputSchema: taskInput, summary: i => `Create task “${i.title}”`, execute: async i => { const task = store.addTask(i); return { text: `Task added: ${task.title}.`, data: task }; } },
    { id: 'tasks.complete', name: 'Complete task', description: 'Marks a task complete.', permission: Permission.READ, inputSchema: i => ({ id: text(i.id, 'task id', 100) }), summary: i => `Complete task ${i.id}`, execute: async i => { const task = store.completeTask(i.id); if (!task) throw new Error('Task not found.'); return { text: `Completed: ${task.title}.`, data: task }; } },
    { id: 'goals.create', name: 'Create goal', description: 'Creates a persistent personal goal.', permission: Permission.READ, inputSchema: goalInput, summary: i => `Create goal “${i.title}”`, execute: async i => { const goal = store.addGoal(i); return { text: `Goal added: ${goal.title}.`, data: goal }; } },
    { id: 'goals.complete', name: 'Complete goal', description: 'Marks a goal complete.', permission: Permission.READ, inputSchema: i => ({ id: text(i.id, 'goal id', 100) }), summary: i => `Complete goal ${i.id}`, execute: async i => { const goal = store.updateGoal(i.id, { status: 'completed' }); if (!goal) throw new Error('Goal not found.'); return { text: `Goal completed: ${goal.title}.`, data: goal }; } },
    { id: 'android.notify', name: 'Android notification', description: 'Sends an approved notification to a connected Android client.', permission: Permission.APPROVAL_REQUIRED, inputSchema: i => ({ title: text(i.title, 'notification title', 120), body: text(i.body, 'notification body', 1000) }), summary: i => `Notify Android: ${i.title}`, execute: async i => { const device = store.read().androidDevices.find(item => item.online); if (!device) throw new Error('No Android client is connected.'); const command = store.queueAndroidCommand({ deviceId: device.id, type: 'notify', payload: { title: i.title, body: i.body } }); return { text: `Notification queued for ${device.name}.`, data: command }; } },
    { id: 'reminders.create', name: 'Create reminder', description: 'Creates a one-time, daily, weekly, or monthly reminder.', permission: Permission.READ, inputSchema: i => { const due = new Date(i.dueAt); if (!i.title || Number.isNaN(due.getTime())) throw new Error('Invalid reminder title or date.'); return { title: text(i.title, 'reminder title', 240), dueAt: due.toISOString(), recurrence: ['daily', 'weekly', 'monthly'].includes(i.recurrence) ? i.recurrence : null }; }, summary: i => `Create reminder “${i.title}”`, execute: async i => { const reminder = store.addReminder(i.title, i.dueAt, i.recurrence); return { text: `Reminder set for ${new Date(i.dueAt).toLocaleString()}.`, data: reminder }; } },
    { id: 'system.inspect', name: 'Inspect system', description: 'Reports local system status.', permission: Permission.READ, inputSchema: () => ({}), summary: () => 'Inspect system status', execute: async () => { const data = tools.systemInfo(); return { text: `${data.hostname}: ${data.memory.freeGB} GB RAM free of ${data.memory.totalGB} GB.`, data }; } },
    { id: 'files.search', name: 'Search files', description: 'Searches the approved user profile.', permission: Permission.READ, inputSchema: i => ({ query: text(i.query, 'file search', 160) }), summary: i => `Search files for “${i.query}”`, execute: async i => { const data = tools.searchFiles(i.query, policy.root, policy); return { text: data.matches.length ? `Found ${data.matches.length} match(es).` : 'No matching files.', data, sources: data.matches.map(m => m.path) }; } },
    { id: 'files.read', name: 'Read file', description: 'Reads supported text and document files in the approved profile.', permission: Permission.READ, inputSchema: i => ({ path: policy.fromUserPath(text(i.path, 'file path', 1024)) }), summary: i => `Read ${path.basename(i.path)}`, execute: async i => { const stat = fs.statSync(i.path); if (!stat.isFile() || stat.size > 10 * 1024 * 1024) throw new Error('Only files up to 10 MB can be read.'); const ext = path.extname(i.path).toLowerCase(); if (['.docx', '.xlsx', '.pptx'].includes(ext)) throw new Error(`Office extraction is not available for ${ext} in this installation.`); const value = fs.readFileSync(i.path, 'utf8'); return { text: value.slice(0, 12000), data: { path: i.path, format: ext || 'text' }, sources: [i.path] }; } },
    { id: 'browser.open', name: 'Open URL', description: 'Opens a validated web URL after explicit approval.', permission: Permission.APPROVAL_REQUIRED, inputSchema: i => { const value = text(i.url, 'URL', 2000); let parsed; try { parsed = new URL(value); } catch { throw new Error('Invalid URL.'); } if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error('Only HTTP and HTTPS URLs can be opened.'); return { url: parsed.toString() }; }, summary: i => `Open ${i.url}`, execute: async i => { const result = await tools.openUrl(i.url); return { text: `Opened ${i.url}.`, data: result, sources: [i.url] }; } },
    { id: 'email.send', name: 'Send email', description: 'Sends a saved email draft through a configured webhook connector after approval.', permission: Permission.APPROVAL_REQUIRED, inputSchema: i => ({ id: text(i.id, 'draft id', 100) }), summary: i => `Send email draft ${i.id}`, execute: async i => { const draft = store.read().emailDrafts?.find(item => item.id === i.id); const connector = store.read().connectors?.email; if (!draft) throw new Error('Email draft not found.'); if (!connector?.configured || connector.enabled === false) throw new Error('Email connector is not configured.'); if (String(connector.provider || '').toLowerCase() !== 'webhook' || !connector.baseUrl) throw new Error('Email connector supports sending only through a configured webhook provider.'); const apiKey = credentials.unseal(connector.apiKey); const response = await fetch(connector.baseUrl, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(apiKey ? { Authorization: `Bearer ${apiKey}` } : {}) }, body: JSON.stringify({ to: draft.to, subject: draft.subject, body: draft.body }) }); if (!response.ok) throw new Error(`Email provider returned HTTP ${response.status}.`); const data = store.read(); const saved = data.emailDrafts.find(item => item.id === draft.id); saved.status = 'sent'; saved.sentAt = new Date().toISOString(); store.write(data); return { text: `Email sent to ${draft.to}.`, data: { id: draft.id, status: 'sent' } }; } },
    { id: 'computer.createFolder', name: 'Create folder', description: 'Creates a folder on the Desktop.', permission: Permission.APPROVAL_REQUIRED, inputSchema: i => ({ name: folderName(i.name), target: policy.namedFolder(folderName(i.name), i.location || 'Desktop') }), summary: i => `Create folder “${i.name}” on Desktop`, execute: async i => { if (fs.existsSync(i.target)) throw new Error('Folder already exists.'); fs.mkdirSync(i.target); if (!fs.statSync(i.target).isDirectory()) throw new Error('Folder verification failed.'); return { text: `Created folder “${i.name}”.`, data: { path: i.target }, sources: [i.target] }; } },
    { id: 'computer.deleteFolder', name: 'Delete folder', description: 'Deletes a folder on the Desktop.', permission: Permission.DESTRUCTIVE, inputSchema: i => ({ name: folderName(i.name), target: policy.namedFolder(folderName(i.name), i.location || 'Desktop') }), summary: i => `Delete folder “${i.name}” from Desktop`, execute: async i => { if (!fs.existsSync(i.target)) throw new Error('Folder not found.'); if (!fs.statSync(i.target).isDirectory()) throw new Error('Target is not a folder.'); fs.rmSync(i.target, { recursive: true, force: false }); if (fs.existsSync(i.target)) throw new Error('Folder deletion verification failed.'); return { text: `Deleted folder “${i.name}”.`, data: { path: i.target } }; } },
    { id: 'command.run', name: 'Run command', description: 'Runs an explicit local command after approval.', permission: Permission.APPROVAL_REQUIRED, inputSchema: i => ({ command: text(i.command, 'command', 1000) }), summary: () => 'Run an explicit local command', execute: async i => { const result = await tools.executeCommand(i.command, true); if (result.exitCode !== 0) throw new Error(result.stderr || `Command failed (${result.exitCode}).`); return { text: result.stdout || 'Command completed.', data: result }; } }
  ];
}
module.exports = { createSkills };
