const { Permission } = require('./permissions');

const definitions = {
  calendar: { collection: 'calendarEvents', prefix: 'event', validate: input => ({ title: required(input.title, 'event title'), startsAt: iso(input.startsAt, 'start time'), endsAt: input.endsAt ? iso(input.endsAt, 'end time') : null, notes: String(input.notes || '').slice(0, 2000) }) },
  finance: { collection: 'financeEntries', prefix: 'money', validate: input => ({ description: required(input.description, 'expense description'), amount: amount(input.amount), currency: String(input.currency || 'USD').slice(0, 8).toUpperCase(), category: String(input.category || 'other').slice(0, 80), occurredAt: input.occurredAt ? iso(input.occurredAt, 'date') : new Date().toISOString() }) },
  health: { collection: 'healthLogs', prefix: 'health', validate: input => ({ metric: required(input.metric, 'health metric'), value: String(input.value || '').slice(0, 200), unit: String(input.unit || '').slice(0, 40), recordedAt: input.recordedAt ? iso(input.recordedAt, 'date') : new Date().toISOString(), note: String(input.note || '').slice(0, 1000) }) },
  automation: { collection: 'automations', prefix: 'auto', validate: input => ({ name: required(input.name, 'automation name'), steps: Array.isArray(input.steps) ? input.steps.slice(0, 20).map(step => String(step).slice(0, 500)) : [], enabled: input.enabled !== false }) }
  ,email: { collection: 'emailDrafts', prefix: 'draft', validate: input => ({ to: required(input.to, 'recipient'), subject: required(input.subject, 'subject'), body: required(input.body, 'email body'), status: input.status === 'sent' ? 'sent' : 'draft' }) }
};
function required(value, label) { if (typeof value !== 'string' || !value.trim() || value.length > 240) throw new Error(`Invalid ${label}.`); return value.trim(); }
function iso(value, label) { const date = new Date(value); if (Number.isNaN(date.getTime())) throw new Error(`Invalid ${label}.`); return date.toISOString(); }
function amount(value) { const number = Number(value); if (!Number.isFinite(number) || number < 0 || number > 1e9) throw new Error('Invalid amount.'); return Math.round(number * 100) / 100; }
function list(store, type) { const definition = definitions[type]; if (!definition) throw new Error('Unknown v2 data type.'); return store.read()[definition.collection] || []; }
function create(store, type, input) { const definition = definitions[type]; if (!definition) throw new Error('Unknown v2 data type.'); const data = store.read(); const item = { id: store.id(definition.prefix), ...definition.validate(input), createdAt: new Date().toISOString() }; data[definition.collection] = data[definition.collection] || []; data[definition.collection].unshift(item); store.write(data); store.log(`${type}.created`, item.title || item.description || item.metric || item.name, { type, recordId: item.id }); return item; }
function update(store, type, id, changes) { const definition = definitions[type]; const data = store.read(); const records = data[definition.collection] || []; const item = records.find(record => record.id === id); if (!item) throw new Error('Record not found.'); const next = definition.validate({ ...item, ...changes }); Object.assign(item, next, { updatedAt: new Date().toISOString() }); store.write(data); store.log(`${type}.updated`, id, { type, recordId: id }); return item; }
function remove(store, type, id) { const definition = definitions[type]; const data = store.read(); const before = (data[definition.collection] || []).length; data[definition.collection] = (data[definition.collection] || []).filter(record => record.id !== id); if (data[definition.collection].length === before) throw new Error('Record not found.'); store.write(data); store.log(`${type}.deleted`, id, { type, recordId: id }); return { id }; }
module.exports = { definitions, list, create, update, remove, Permission };
